version: '3.8'

services:
  # app:
  #   container_name: next_app
  #   image: bj:latest
  #   working_dir: /app
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000" 
  #   depends_on:
  #     - db
  #   command: npm run start

  db:
    container_name: postgres_db
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  nginx:
    container_name: proxy_nginx
    depends_on:
      # - app
      - db
      - pgadmin
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    restart: always

  pgadmin:
    container_name: pgadmin
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    expose:
      - "80"
    restart: always
